/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.12
 * Generated at: 2024-08-05 21:26:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/UTP%20TRABAJOS/MARZO%202024/DESARROLLO%20WEB%20INTEGRADO/ATF/Proyecto_TaypaFastFood/build/web/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602891972000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1721166959198L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>TAYPA FASTFOOD</title>\n");
      out.write("    <!-- libreria para que aparezca animacion en la pag web -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\" />\n");
      out.write("    <!--  para que aparezca el icono en la pestaña -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/IMGS/IMGS ICON/logo taypa.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CSS/index.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div class=\"contenedor\">\n");
      out.write("        <!--  header menu movible -->\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <div class=\"logotivo\">\n");
      out.write("                <img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/IMGS/IMGS ICON/logo taypa.png\" alt=\"Imagen logotivo\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <p><span>FAST<br>FOOD</span></p>\n");
      out.write("            </div>\n");
      out.write("            <nav class=\"menu\">\n");
      out.write("                <ul class=\"navegacion\">\n");
      out.write("                    <li><a href=\"index.jsp\">&#x25A3;INICIO</a></li>\n");
      out.write("                    <li><a href=\"nosotros.jsp\">&#x25A3;NOSOTROS</a></li>\n");
      out.write("                    <li><a href=\"tienda.jsp\">&#x25A3;TIENDA</a></li>\n");
      out.write("                    <li><a href=\"CONTACTANOS.jsp\">&#x25A3;CONTACTANOS</a></li>\n");
      out.write("                    <li><a href=\"Ingresar.jsp\">&#x25A3;INICIAR SESIÓN</a><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registrase.jsp\">REGISTRARSE</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        </main><br><br><br><br><br><br><br><br><br><br>\n");
      out.write("        <aside class=\"presentacion\">\n");
      out.write("            <div class=\"informacion\">\n");
      out.write("                <h1>Ordena tu comida favorita </h1>\n");
      out.write("                <div class=\"textopublicitario\">\n");
      out.write("                    <p>Hola, nuestra deliciosa comida esta esperando por ti.</p><br>\n");
      out.write("                    <p>\"¡Te damos la bienvenida a nuestro mundo de sabores irresistibles! <br>\n");
      out.write("                        En TAYPA FASTFOOD, siempre estamos a tu alcance con nuestra deliciosa comida rápida\n");
      out.write("                        esperándote.\"</p><br>\n");
      out.write("                    <p>Siempre estamos cerca de ti con nuestra comida rapida en TAYPA FASTFOOD</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"informacion--boton\">\n");
      out.write("                    <button type=\"button\"><a href=\"tienda.jsp\">Explorar Comida</a></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"presentacion--imagen\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/IMGS/IMGS TAYPA FASTFOOD PROYECTO/portada.png\" alt=\"Imagen presentacion\">\n");
      out.write("            </div>\n");
      out.write("        </aside><br><br>\n");
      out.write("\n");
      out.write("                <h2 class=\"anunciovideos\">ANUNCIOS</h2>\n");
      out.write("            <!-- autoplay loop muted es para que el video se reproduzca sucesivamente -->\n");
      out.write("            <video class=\"video1\" autoplay loop muted>\n");
      out.write("                <source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VIDEOS/VIDEO PUBLICITARIO.mp4\" type=\"video/mp4\">\n");
      out.write("            </video>\n");
      out.write("            <video class=\"video2\" autoplay loop muted>\n");
      out.write("                <source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VIDEOS/VIDEO PUBLICITARIO 2.mp4\" type=\"video/mp4\">\n");
      out.write("            </video><br>\n");
      out.write("            <br>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("        <main class=\"comida\">\n");
      out.write("            <h2 class=\"comida--titulo\">Nuestros platillos &#x2926;</h2>\n");
      out.write("            <div class=\"platos\">\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/HAMBURGUESA DOBLE CARNE.jpg\"\n");
      out.write("                        alt=\"HAMBURGUESA DOBLE CARNE\">\n");
      out.write("                    <h1>&#x22B3;Hamburguesa Doble Carne&#x22B2;</h1>\n");
      out.write("                    <p>•Queso<br>\n");
      out.write("                        •Hamburguesa artesanal(x2)<br>\n");
      out.write("                        •Huevo frito<br>\n");
      out.write("                        •Papas al hilo<br>\n");
      out.write("                        •Pan</p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/CLUB SANDWICH.jpg\" alt=\"CLUB SANDWICH\">\n");
      out.write("                    <h1>&#x22B3;Club Sandwich&#x22B2;</h1>\n");
      out.write("                    <p>•Palta<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Chorizo<br>\n");
      out.write("                        •Pan<br>\n");
      out.write("                        •Queso<br>\n");
      out.write("                        •Pollo desilachado<br>\n");
      out.write("                        •Tomate<br>\n");
      out.write("                        •Huevo frito\n");
      out.write("                    </p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/SALCHI ROYAL.jpg\" alt=\"SALCHI ROYAL\">\n");
      out.write("                    <h1>&#x22B3;Salchi Royal&#x22B2;</h1>\n");
      out.write("                    <p>•Queso<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Salchicha nacional<br>\n");
      out.write("                        •Huevo frito<br>\n");
      out.write("                        •Ensalada de lechuga fresca<br>\n");
      out.write("                        •Salsas caceras </p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/SALCHI TAYPA.jpg\" alt=\"SALCHI TAYPA\">\n");
      out.write("                    <h1>&#x22B3;Salchi Taypa&#x22B2;</h1>\n");
      out.write("                    <p>•Chorizo<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Salchicha nacional<br>\n");
      out.write("                        •Huevo frito<br>\n");
      out.write("                        •Ensalada de lechuga fresca<br>\n");
      out.write("                        •Trozos de carne<br>\n");
      out.write("                        •Tocino<br>\n");
      out.write("                        •Salsas caceras</p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/BISTECK A LO POBRE.jpg\" alt=\"BISTECK A LO POBRE\">\n");
      out.write("                    <h1>&#x22B3;Bisteck a lo Pobre&#x22B2;</h1>\n");
      out.write("                    <p>•Bisteck de carne a la plancha<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Huevo frito<br>\n");
      out.write("                        •Arroz<br>\n");
      out.write("                        •Platano frito<br>\n");
      out.write("                        •Salsas caceras</p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/MOSTRITO.jpg\" alt=\"MOSTRITO \">\n");
      out.write("                    <h1>&#x22B3;Mostrito&#x22B2;</h1>\n");
      out.write("                    <p>•Crujiente y jugosa alita de pollo broaster<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Huevo frito<br>\n");
      out.write("                        •Arroz chaufa<br>\n");
      out.write("                        •Ensalada de lechuga fresa<br>\n");
      out.write("                        •Salsas caceras</p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/TALLARIN SALTADO.jpg\" alt=\"TALLARIN SALTADO \">\n");
      out.write("                    <h1>&#x22B3;Tallarin Saltado&#x22B2;</h1>\n");
      out.write("                    <p>•Deliciosos y jugosos tallarines saltados acompañados de trozos de carne o pollo<br>\n");
      out.write("                        •Tomate<br>\n");
      out.write("                        •Cebollita china. </p>\n");
      out.write("                </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/ALITAS BBQ.png\" alt=\"ALITAS BBQ \">\n");
      out.write("                    <h1>&#x22B3;Alitas BBQ&#x22B2;</h1>\n");
      out.write("                    <p>•Jugosas y deliciosas piezas de pollo bañadas en salsa BBQ<br>\n");
      out.write("                        •Papas fritas<br>\n");
      out.write("                        •Ensalada de lechuga fresca<br>\n");
      out.write("                        •Salsas caceras</p>\n");
      out.write("                </article>\n");
      out.write("            </div><br><br>\n");
      out.write("            <h2 class=\"comida--titulo\">Nuestros Jugos y Bebidas &#x2926;</h2>\n");
      out.write("            <div class=\"platos\">\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/bebidas taypa.jpg\" alt=\"bebidas taypa\">\n");
      out.write("                    <h1>&#x22B3;Bebidas TAYPA FASTFOOD&#x22B2;</h1>\n");
      out.write("                    <p>•Chicha <br>\n");
      out.write("                        •Limonada <br>\n");
      out.write("                        •Gaseosas <br>\n");
      out.write("                        •Refrescos</p>\n");
      out.write("                    </article>\n");
      out.write("                <article class=\"plato\">\n");
      out.write("                    <img src=\"IMGS/IMGS TAYPA FASTFOOD PROYECTO/jugos taypa.jpg\" alt=\"jugos taypa\">\n");
      out.write("                    <h1>&#x22B3;Jugos TAYPA FASTFOOD&#x22B2;</h1>\n");
      out.write("                    <p>•Papaya <br>\n");
      out.write("                        •Fresa <br>\n");
      out.write("                        •Piña <br>\n");
      out.write("                        •Mango <br>\n");
      out.write("                        •Mixto\n");
      out.write("                    </p>\n");
      out.write("                </article>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<section class=\"Contáctanos\" id=\"Contáctanos\">\n");
      out.write("   <br><br><br>\n");
      out.write("    <h1 class=\"heading\"><span> Info </span> Contáctanos</h1><br><br>\n");
      out.write("    <h2 class=\"heading\">Encuentra tu TAYPA FAST FOOD &#x2926;</h2>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <iframe class=\"map\"\n");
      out.write("            src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3901.6309800186887!2d-77.05362022410452!3d-12.068891742314813!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c8e14e1b2e55%3A0x3c67f15e15f551ff!2sD&#39;Roceli%20Caf%C3%A9!5e0!3m2!1ses-419!2spe!4v1696826185620!5m2!1ses-419!2spe\"\n");
      out.write("            width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\"\n");
      out.write("            referrerpolicy=\"no-referrer-when-downgrade\">\n");
      out.write("        </iframe>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("   <marquee scrolldelay=\"1\" style=\"background-color: rgb(173, 44, 167);font-size:45px\">\n");
      out.write("        <h4 class=\"textofinal\">©2024 TAYPA FAST FOOD Peru Company. Todos los Derechos Reservados.</h4>\n");
      out.write("    </marquee>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
